/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import dao.DatabaseConection;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author linhy
 */
public class Dangky extends javax.swing.JFrame {

    /**
     * Creates new form dangky
     */
    public Dangky() {
        initComponents();
        lbldangnhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrgioitinh = new javax.swing.ButtonGroup();
        btngrdoituong = new javax.swing.ButtonGroup();
        lblhoten = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblsodienthoai = new javax.swing.JLabel();
        lblgioitinh = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblngaysinh = new javax.swing.JLabel();
        lbldiachi = new javax.swing.JLabel();
        lblmatkhau = new javax.swing.JLabel();
        lblnhaplai = new javax.swing.JLabel();
        btndangky = new javax.swing.JButton();
        txtsodienthoai = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        txttaikhoan = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        radnam = new javax.swing.JRadioButton();
        radnu = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lbldangnhap = new javax.swing.JLabel();
        passnhaplai = new javax.swing.JPasswordField();
        passmatkhau = new javax.swing.JPasswordField();
        lbldoithuong = new javax.swing.JLabel();
        radnguoithue = new javax.swing.JRadioButton();
        radchutro = new javax.swing.JRadioButton();
        jcldngaysinh = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblhoten.setText("Họ tên");
        getContentPane().add(lblhoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 47, -1));

        lblemail.setText("Tài khoản");
        getContentPane().add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 182, 65, -1));

        lblsodienthoai.setText("Số điện thoại");
        getContentPane().add(lblsodienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 261, 512, -1));

        lblgioitinh.setText("Giới tính");
        getContentPane().add(lblgioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 324, 70, 22));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TẠO TÀI KHOẢN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, -1));

        lblngaysinh.setText("Ngày sinh");
        getContentPane().add(lblngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, -1));

        lbldiachi.setText("Địa chỉ");
        getContentPane().add(lbldiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 182, 45, -1));

        lblmatkhau.setText("Mật khẩu");
        getContentPane().add(lblmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 261, -1, -1));

        lblnhaplai.setText("Nhập lại mật khẩu");
        getContentPane().add(lblnhaplai, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 324, -1, -1));

        btndangky.setText("ĐĂNG KÝ");
        btndangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangkyActionPerformed(evt);
            }
        });
        getContentPane().add(btndangky, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 110, -1));

        txtsodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsodienthoaiActionPerformed(evt);
            }
        });
        getContentPane().add(txtsodienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 284, 195, 28));
        getContentPane().add(txthoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 131, 195, 28));
        getContentPane().add(txttaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 195, 28));
        getContentPane().add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 210, 195, 28));

        btngrgioitinh.add(radnam);
        radnam.setText("Nam");
        getContentPane().add(radnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 345, 98, -1));

        btngrgioitinh.add(radnu);
        radnu.setText("Nữ");
        getContentPane().add(radnu, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 372, 98, -1));

        jLabel1.setText("Bạn đã có tài khoản !");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 119, -1));

        lbldangnhap.setForeground(new java.awt.Color(0, 0, 153));
        lbldangnhap.setText("Đăng nhập");
        lbldangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangnhapMouseClicked(evt);
            }
        });
        getContentPane().add(lbldangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));
        getContentPane().add(passnhaplai, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 352, 195, 26));
        getContentPane().add(passmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 285, 195, 26));

        lbldoithuong.setText("Đối tượng");
        getContentPane().add(lbldoithuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 323, -1, -1));

        btngrdoituong.add(radnguoithue);
        radnguoithue.setText("Người thuê");
        getContentPane().add(radnguoithue, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 345, 98, -1));

        btngrdoituong.add(radchutro);
        radchutro.setText("Chủ trọ");
        getContentPane().add(radchutro, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 372, 98, -1));
        getContentPane().add(jcldngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 200, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/anhnen.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsodienthoaiActionPerformed

    private void btndangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangkyActionPerformed
        // TODO add your handling code here:
        String hoten = txthoten.getText();
        String taikhoan = txttaikhoan.getText();
        String sodienthoai = txtsodienthoai.getText();
        // Get the selected date from the JCalendar (jcldngaysinh)
        java.util.Date utilDate = jcldngaysinh.getDate();

        // Check if the date is not null
        if (utilDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh!");
            return;
        }
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        String matkhau = new String(passmatkhau.getPassword());
        String nhaplaiMatKhau = new String(passnhaplai.getPassword());
        String diachi = txtdiachi.getText();
        String gioitinh = radnam.isSelected() ? "Nam" : "Nữ";
        String doituong = radnguoithue.isSelected() ? "Người Thuê" : "Chủ trọ";
        if (hoten.isEmpty() || taikhoan.isEmpty() || sodienthoai.isEmpty() || matkhau.isEmpty() || diachi.isEmpty() || gioitinh.isEmpty() || doituong.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        if (!matkhau.equals(nhaplaiMatKhau)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không khớp!");
            return;
        }
        // Kiểm tra độ mạnh của mật khẩu
        if (!matkhau.matches("^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=\\S+$).{8,}$")) {
            JOptionPane.showMessageDialog(this, "Mật khẩu phải có ít nhất 8 ký tự, bao gồm ít nhất 1 chữ in hoa, 1 ký tự đặc biệt và không có khoảng trắng.");
            return;
        }

        // Kiểm tra số điện thoại
        if (!sodienthoai.matches("^0\\d{9}$")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải bắt đầu bằng số 0 và có đúng 10 chữ số.");
            return;
        }
        try (Connection conn = DatabaseConection.getConnection()) {
            String sql = "INSERT INTO dangnhap ([name],[usename], [password], [phone], [Adress], [Datetime], [confirmpassword], [sex],[role]) VALUES (?, ?, ?, ?, ?, ?, ?,?,?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, hoten);
            pstmt.setString(2, taikhoan);
            pstmt.setString(3, matkhau);
            pstmt.setString(4, sodienthoai);
            pstmt.setString(5, diachi); // Adjust this if you parse dates
            pstmt.setDate(6, sqlDate);
            pstmt.setString(7, nhaplaiMatKhau);
            pstmt.setString(8, gioitinh);
            pstmt.setString(9, doituong);

            int rowsInserted = pstmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Đăng ký thành công!");
                // Redirect to login form if needed
                Dangnhap dangnhap = new Dangnhap();
                dangnhap.setVisible(true);
                dangnhap.setLocationRelativeTo(null);
                this.dispose();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi đăng ký: " + e.getMessage());
        }
    }//GEN-LAST:event_btndangkyActionPerformed
    // Hàm kiểm tra độ phức tạp của mật khẩu

    private void lbldangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangnhapMouseClicked
        // TODO add your handling code here:
        Dangnhap dangnhap = new Dangnhap();
        dangnhap.setVisible(true);
        dangnhap.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lbldangnhapMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dangky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dangky dangky = new Dangky();
                dangky.setVisible(true);
                dangky.setLocationRelativeTo(null);
                dangky.setResizable(false);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangky;
    private javax.swing.ButtonGroup btngrdoituong;
    private javax.swing.ButtonGroup btngrgioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser jcldngaysinh;
    private javax.swing.JLabel lbldangnhap;
    private javax.swing.JLabel lbldiachi;
    private javax.swing.JLabel lbldoithuong;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblgioitinh;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblmatkhau;
    private javax.swing.JLabel lblngaysinh;
    private javax.swing.JLabel lblnhaplai;
    private javax.swing.JLabel lblsodienthoai;
    private javax.swing.JPasswordField passmatkhau;
    private javax.swing.JPasswordField passnhaplai;
    private javax.swing.JRadioButton radchutro;
    private javax.swing.JRadioButton radnam;
    private javax.swing.JRadioButton radnguoithue;
    private javax.swing.JRadioButton radnu;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtsodienthoai;
    private javax.swing.JTextField txttaikhoan;
    // End of variables declaration//GEN-END:variables
}
