/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import dao.DangNhapDao;
import dao.DatabaseConection;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.prefs.Preferences;
/**
 *
 * @author linhy
 */
public class Dangnhap extends javax.swing.JFrame {
 private Preferences prefs; // Để lưu thông tin người dùng
    /**
     * Creates new form NewJFrame
     */
    public Dangnhap() {
        initComponents();
        lbldangky.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
         
        // Khởi tạo Preferences để lưu thông tin
        prefs = Preferences.userNodeForPackage(Dangnhap.class);
        
        // Lấy thông tin từ Preferences và điền vào các trường
        String savedUsername = prefs.get("username", ""); // Lấy tài khoản đã lưu
        String savedPassword = prefs.get("password", ""); // Lấy mật khẩu đã lưu

        txttaikhoan.setText(savedUsername);
        passmatkhau.setText(savedPassword);
        chknhomatkhau.setSelected(!savedUsername.isEmpty()); // Kiểm tra và đặt trạng thái của checkbox
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbltaikhoan = new javax.swing.JLabel();
        lblmatkhau = new javax.swing.JLabel();
        txttaikhoan = new javax.swing.JTextField();
        btndangnhap = new javax.swing.JButton();
        passmatkhau = new javax.swing.JPasswordField();
        chknhomatkhau = new javax.swing.JCheckBox();
        lblquenmatkhau = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbldangky = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");

        lbltaikhoan.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lbltaikhoan.setText("Tài khoản");

        lblmatkhau.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblmatkhau.setText("Mật khẩu");

        txttaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttaikhoanActionPerformed(evt);
            }
        });

        btndangnhap.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btndangnhap.setText("Đăng nhập ");
        btndangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangnhapActionPerformed(evt);
            }
        });

        chknhomatkhau.setText("Nhớ mật khẩu");
        chknhomatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chknhomatkhauActionPerformed(evt);
            }
        });

        lblquenmatkhau.setForeground(new java.awt.Color(0, 0, 204));
        lblquenmatkhau.setText("Quên mật khẩu?");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Bạn chưa có tài khoản ?");

        lbldangky.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbldangky.setForeground(new java.awt.Color(0, 0, 204));
        lbldangky.setText("Đăng ký");
        lbldangky.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangkyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chknhomatkhau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblquenmatkhau))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldangky, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltaikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblquenmatkhau)
                    .addComponent(chknhomatkhau))
                .addGap(22, 22, 22)
                .addComponent(btndangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbldangky))
                .addGap(14, 14, 14))
        );

        lbltaikhoan.getAccessibleContext().setAccessibleName("");
        lblmatkhau.getAccessibleContext().setAccessibleName("");
        txttaikhoan.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttaikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttaikhoanActionPerformed

    private void btndangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangnhapActionPerformed
        // TODO add your handling code here:
        /*String usename = txttaikhoan.getText();
        String password = new String(passmatkhau.getPassword());

        try (Connection conn = bdconnect.getConnection()) {
            String sql = "SELECT * FROM dangnhap WHERE usename = ? AND password = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, usename);
            stmt.setString(2, password);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
//                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                Mainform mainform = new Mainform();
                mainform.setVisible(true);
                dispose(); // Đóng form đăng nhập
            } else {
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại. Vui lòng thử lại.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + ex.getMessage());
        }*/
        String usename = txttaikhoan.getText();
        String password = new String(passmatkhau.getPassword());

        try (Connection conn = DatabaseConection.getConnection()) {
            String sql = "SELECT * FROM dangnhap WHERE usename = ? AND password = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, usename);
            stmt.setString(2, password);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                // Lưu tài khoản và mật khẩu nếu checkbox được chọn
                if (chknhomatkhau.isSelected()) {
                    prefs.put("username", usename);
                    prefs.put("password", password);
                } else {
                    // Xóa thông tin nếu checkbox không được chọn
                    prefs.remove("username");
                    prefs.remove("password");
                }

                Mainform mainform = new Mainform(DangNhapDao.getDangNhap(usename));
                mainform.setVisible(true);
                mainform.setLocationRelativeTo(null);
                dispose(); // Đóng form đăng nhập
            } else {
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại. Vui lòng thử lại.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + ex.getMessage());
        }
    }//GEN-LAST:event_btndangnhapActionPerformed

    private void chknhomatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chknhomatkhauActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_chknhomatkhauActionPerformed

    private void lbldangkyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangkyMouseClicked
        // TODO add your handling code here:
        Dangky dangky = new Dangky();
        dangky.setVisible(true);
        dangky.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_lbldangkyMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dangnhap dangNhap = new Dangnhap();
                dangNhap.setVisible(true);
                dangNhap.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndangnhap;
    private javax.swing.JCheckBox chknhomatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbldangky;
    private javax.swing.JLabel lblmatkhau;
    private javax.swing.JLabel lblquenmatkhau;
    private javax.swing.JLabel lbltaikhoan;
    private javax.swing.JPasswordField passmatkhau;
    private javax.swing.JTextField txttaikhoan;
    // End of variables declaration//GEN-END:variables
}
