/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import dao.DatabaseConection;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.sql.SQLException;
import java.sql.*;
import javax.swing.JFileChooser;
import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.quanly;

/**
 *
 * @author linhy
 */
public class updatephong extends javax.swing.JFrame {

    /**
     * Creates new form updatephong
     */
    public updatephong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblloaiphong = new javax.swing.JLabel();
        lblloaitin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblgiaphong = new javax.swing.JLabel();
        lbldientich = new javax.swing.JLabel();
        lbldiachi = new javax.swing.JLabel();
        cobloaitin = new javax.swing.JComboBox<>();
        cobloaiphong = new javax.swing.JComboBox<>();
        txtgiaphong = new javax.swing.JTextField();
        txtdientich = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        btnanh = new javax.swing.JButton();
        lblanh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblthongtinphong = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        btndangtin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblloaiphong.setText("Loại phòng");

        lblloaitin.setText("Loại tin");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ĐĂNG TIN");

        lblgiaphong.setText("Giá phòng");

        lbldientich.setText("Diện tích");

        lbldiachi.setText("Địa chỉ");

        cobloaitin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cho thuê", "Tìm người ở ghép" }));

        cobloaiphong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng", "Căn hộ", "Căn hộ mini", "Nhà nguyên căn" }));

        btnanh.setText("Chọn ảnh");
        btnanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanhActionPerformed(evt);
            }
        });

        tblthongtinphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại tin", "Loại phòng", "Giá phòng", "Địa chỉ", "Diện tích"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblthongtinphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthongtinphongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblthongtinphong);

        btnthem.setText("Thêm ");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthemmoi.setText("Thêm mới");
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });

        btndangtin.setText("ĐĂNG TIN");
        btndangtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangtinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbldiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(lbldientich, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblgiaphong)
                                            .addComponent(lblloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblloaitin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cobloaiphong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cobloaitin, 0, 170, Short.MAX_VALUE)))
                                    .addComponent(txtgiaphong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnthemmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtdientich, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(90, 90, 90)
                                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(btnanh, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnxoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(btndangtin, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblloaitin)
                            .addComponent(cobloaitin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblloaiphong)
                            .addComponent(cobloaiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(lblgiaphong)
                        .addGap(18, 18, 18)
                        .addComponent(txtgiaphong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldiachi)
                    .addComponent(lbldientich))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdientich, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnanh, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnsua)
                    .addComponent(btnxoa)
                    .addComponent(btnthemmoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btndangtin)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ArrayList<quanly> ArrayQL = new ArrayList<quanly>();
    String duongdananh = "D:\\icon";

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    private void btnanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanhActionPerformed
        try {
            JFileChooser f = new JFileChooser("D:\\icon");
            f.setDialogTitle("Mo file");
            f.showOpenDialog(null);
            File fteanh = f.getSelectedFile();
            duongdananh = fteanh.getAbsolutePath();

            lblanh.setIcon(ResizeImage(String.valueOf(duongdananh)));
            System.out.println(duongdananh);

        } catch (Exception e) {
            System.out.println("chua chon anh");
            System.out.println(duongdananh);
        }
    }//GEN-LAST:event_btnanhActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        FilDataToArrayList();
        FilDataToArrayListTable();
    }//GEN-LAST:event_btnthemActionPerformed
    public void FilDataToArrayList() {
        quanly ql = new quanly();
        ql.setLoaitin(cobloaitin.getSelectedItem().toString()); // Corrected to getSelectedItem
        ql.setLoaiphong(cobloaiphong.getSelectedItem().toString()); // Corrected to getSelectedItem
        ql.setGiaphong(Double.parseDouble(txtgiaphong.getText()));
        ql.setDiaci(txtdiachi.getText());
        ql.setDientich(txtdientich.getText());
        ql.setAnh(duongdananh);
        ArrayQL.add(ql);
    }

    public void FilDataToArrayListTable() {
        DefaultTableModel model = (DefaultTableModel) tblthongtinphong.getModel();
        model.setRowCount(0);
        for (quanly ql : ArrayQL) {
            model.addRow(new Object[]{ql.getLoaitin(), ql.getLoaiphong(), ql.getGiaphong(), ql.getDiaci(), ql.getDientich()});

        }
//        for(quanly ql : ArrayQL)
//        {
//            Vector vec = new Vector();
//            vec.add(ql.getLoaitin());
//            vec.add(ql.getLoaiphong());
//            vec.add(ql.getGiaphong());
//            vec.add(ql.getDiaci());
//            vec.add(ql.getDientich());
//            vec.add(ql.getAnh());
//            model.addRow(vec);
//        }
    }
    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        quanly ql = new quanly();
        ql.setLoaitin(cobloaitin.getSelectedItem().toString());
        ql.setLoaiphong(cobloaiphong.getSelectedItem().toString());
        ql.setGiaphong(Double.parseDouble(txtgiaphong.getText()));
        ql.setDiaci(txtdiachi.getText());
        ql.setDientich(txtdientich.getText());
        ql.setAnh(duongdananh);
        ArrayQL.set(vitri, ql);
        FilDataToArrayListTable();
        JOptionPane.showMessageDialog(this, "sua thanh cong");
    }//GEN-LAST:event_btnsuaActionPerformed
    public int vitri = -1;
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        ArrayQL.remove(vitri);
        FilDataToArrayListTable();
    }//GEN-LAST:event_btnxoaActionPerformed
    public void FillDateToControl() {
        cobloaitin.setSelectedItem(ArrayQL.get(vitri).getLoaitin());
        cobloaiphong.setSelectedItem(ArrayQL.get(vitri).getLoaiphong());
        txtgiaphong.setText(String.valueOf(ArrayQL.get(vitri).getGiaphong()));
        txtdiachi.setText(ArrayQL.get(vitri).getDiaci());
        txtdientich.setText(ArrayQL.get(vitri).getDientich());
        lblanh.setIcon(ResizeImage(ArrayQL.get(vitri).getAnh()));
    }
    private void tblthongtinphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthongtinphongMouseClicked
        vitri = tblthongtinphong.getSelectedRow();
        FillDateToControl();
    }//GEN-LAST:event_tblthongtinphongMouseClicked

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        txtgiaphong.setText("");
        txtdiachi.setText("");
        txtdientich.setText("");
    }//GEN-LAST:event_btnthemmoiActionPerformed
    private void loadData() {
        try (Connection conn = DatabaseConection.getConnection()) {
            String sql = "SELECT * FROM thongtinphong";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            DefaultTableModel model = (DefaultTableModel) tblthongtinphong.getModel();
            model.setRowCount(0); // Clear existing rows

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("loaitin"),
                    rs.getString("loaiphong"),
                    rs.getDouble("gia"),
                    rs.getString("diachi"),
                    rs.getString("dientich")
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu!");
        }
    }
    private void btndangtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangtinActionPerformed

        String loaitin = cobloaitin.getSelectedItem().toString();
        String loaiphong = cobloaiphong.getSelectedItem().toString();
        double giaphong;
        try {
            giaphong = Double.parseDouble(txtgiaphong.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá phòng không hợp lệ! Vui lòng nhập lại.");
            return;
        }
        String diachi = txtdiachi.getText();
        String dientich = txtdientich.getText();
        String anh = duongdananh;

        // Check for empty fields
        if (loaitin.isEmpty() || loaiphong.isEmpty() || diachi.isEmpty() || dientich.isEmpty() || anh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        // Insert data into database
        try (Connection conn = DatabaseConection.getConnection()) {
            String sql = "INSERT INTO thongtinphong (loaitin, loaiphong, gia, diachi, dientich, anh) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, loaitin);
            stmt.setString(2, loaiphong);
            stmt.setDouble(3, giaphong);
            stmt.setString(4, diachi);
            stmt.setString(5, dientich);
            stmt.setString(6, anh);

            int rowsAffected = stmt.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Đăng tin thành công!");
                loadData(); // Reload all data to refresh the table
            } else {
                JOptionPane.showMessageDialog(this, "Đăng tin thất bại, vui lòng thử lại.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + ex.getMessage());
        }

        // Clear input fields
        txtgiaphong.setText("");
        txtdiachi.setText("");
        txtdientich.setText("");
        duongdananh = "";
        cobloaitin.setSelectedIndex(0);
        cobloaiphong.setSelectedIndex(0);

    }//GEN-LAST:event_btndangtinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatephong().setVisible(true);
            }
        });
    }

    @Override
    public void setDefaultCloseOperation(int operation) {
        if (operation != DO_NOTHING_ON_CLOSE
                && operation != HIDE_ON_CLOSE
                && operation != DISPOSE_ON_CLOSE
                && operation != EXIT_ON_CLOSE) {
            throw new IllegalArgumentException("defaultCloseOperation must be"
                    + " one of: DO_NOTHING_ON_CLOSE, HIDE_ON_CLOSE,"
                    + " DISPOSE_ON_CLOSE, or EXIT_ON_CLOSE");
        }

        if (operation == EXIT_ON_CLOSE) {
            setVisible(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanh;
    private javax.swing.JButton btndangtin;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cobloaiphong;
    private javax.swing.JComboBox<String> cobloaitin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblanh;
    private javax.swing.JLabel lbldiachi;
    private javax.swing.JLabel lbldientich;
    private javax.swing.JLabel lblgiaphong;
    private javax.swing.JLabel lblloaiphong;
    private javax.swing.JLabel lblloaitin;
    private javax.swing.JTable tblthongtinphong;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtdientich;
    private javax.swing.JTextField txtgiaphong;
    // End of variables declaration//GEN-END:variables

}
