/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp;

import dao.PhongDao;
import java.awt.Image;
import javax.swing.JFileChooser;
import java.io.File;
import java.util.LinkedList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DangnhapInfo;
import model.PhongInfo;

/**
 *
 * @author linhy
 */
public class updatephong extends javax.swing.JFrame {

    private DangnhapInfo dangnhapInfo;

    /**
     * Creates new form updatephong
     */
    public updatephong() {
        initComponents();
    }

    public updatephong(DangnhapInfo dangnhapInfo) {
        initComponents();
        this.dangnhapInfo = dangnhapInfo;
        displayPhongByUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblloaiphong = new javax.swing.JLabel();
        lblloaitin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblgiaphong = new javax.swing.JLabel();
        lbldientich = new javax.swing.JLabel();
        lbldiachi = new javax.swing.JLabel();
        cobloaitin = new javax.swing.JComboBox<>();
        cobloaiphong = new javax.swing.JComboBox<>();
        txtgiaphong = new javax.swing.JTextField();
        txtdientich = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        btnanh = new javax.swing.JButton();
        lblanh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblthongtinphong = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthemmoi = new javax.swing.JButton();
        btndangtin = new javax.swing.JButton();
        lblbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblloaiphong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblloaiphong.setText("Loại phòng");
        getContentPane().add(lblloaiphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 71, 20));

        lblloaitin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblloaitin.setText("Loại tin");
        getContentPane().add(lblloaitin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ĐĂNG TIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 720, -1));

        lblgiaphong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblgiaphong.setText("Giá phòng");
        getContentPane().add(lblgiaphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lbldientich.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbldientich.setText("Diện tích");
        getContentPane().add(lbldientich, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 71, -1));

        lbldiachi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbldiachi.setText("Địa chỉ");
        getContentPane().add(lbldiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        cobloaitin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cho thuê", "Tìm người ở ghép" }));
        getContentPane().add(cobloaitin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 180, 30));

        cobloaiphong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng", "Căn hộ", "Căn hộ mini", "Nhà nguyên căn" }));
        cobloaiphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobloaiphongActionPerformed(evt);
            }
        });
        getContentPane().add(cobloaiphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, 30));
        getContentPane().add(txtgiaphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 30));
        getContentPane().add(txtdientich, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 265, 180, 30));

        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        getContentPane().add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, 30));

        btnanh.setText("Chọn ảnh");
        btnanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnanhActionPerformed(evt);
            }
        });
        getContentPane().add(btnanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 124, 27));
        getContentPane().add(lblanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 64, 371, 211));

        tblthongtinphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại tin", "Loại phòng", "Giá phòng", "Địa chỉ", "Diện tích"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblthongtinphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblthongtinphongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblthongtinphong);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 656, 268));

        btnthem.setText("Thêm ");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        getContentPane().add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 103, -1));

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 103, -1));

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 103, -1));

        btnthemmoi.setText("Thêm mới");
        btnthemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemmoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnthemmoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 103, -1));

        btndangtin.setText("ĐĂNG TIN");
        btndangtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangtinActionPerformed(evt);
            }
        });
        getContentPane().add(btndangtin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, 114, -1));

        lblbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/anhnen(1).jpg"))); // NOI18N
        getContentPane().add(lblbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 720, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private List<PhongInfo> ArrayQL = new LinkedList<>();
    private List<PhongInfo> listAdd = new LinkedList<>();
    private List<PhongInfo> listUpdate = new LinkedList<>();
    String duongdananh = "";

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(lblanh.getWidth(), lblanh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    private void btnanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnanhActionPerformed
        try {
            duongdananh = "D:\\Learning\\JavaApp\\src\\icon";
            JFileChooser f = new JFileChooser("D:\\Learning\\JavaApp\\src\\icon");
            f.setDialogTitle("Mo file");
            f.showOpenDialog(null);
            File fteanh = f.getSelectedFile();
            duongdananh = fteanh.getAbsolutePath();

            lblanh.setIcon(ResizeImage(String.valueOf(duongdananh)));
            System.out.println(duongdananh);

        } catch (Exception e) {
            System.out.println("chua chon anh");
            System.out.println(duongdananh);
        }
    }//GEN-LAST:event_btnanhActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        String loaitin = cobloaitin.getSelectedItem().toString();
        String loaiphong = cobloaiphong.getSelectedItem().toString();
        String giaphongStr = txtgiaphong.getText();
        double giaphong;
        try {
            giaphong = Double.parseDouble(giaphongStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá phòng không hợp lệ! Vui lòng nhập lại.");
            return;
        }
        String diachi = txtdiachi.getText();
        String dientich = txtdientich.getText();
        String anh = duongdananh;
        if (loaitin.isEmpty() || loaiphong.isEmpty() || diachi.isEmpty() || dientich.isEmpty() || anh.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin!");
            return;
        }

        FilDataToArrayList();
        FilDataToArrayListTable();
        clearPhongInfo();
    }//GEN-LAST:event_btnthemActionPerformed
    public void FilDataToArrayList() {
        PhongInfo ql = new PhongInfo();
        ql.setLoaitin(cobloaitin.getSelectedItem().toString()); // Corrected to getSelectedItem
        ql.setLoaiphong(cobloaiphong.getSelectedItem().toString()); // Corrected to getSelectedItem
        ql.setGiaphong(Double.parseDouble(txtgiaphong.getText()));
        ql.setDiaci(txtdiachi.getText());
        ql.setDientich(txtdientich.getText());
        ql.setAnh(duongdananh);
        ql.setId_name(dangnhapInfo.getId_name());
        ArrayQL.add(ql);
        // thêm vào list phòng cần add
        listAdd.add(ql);
    }

    public void FilDataToArrayListTable() {
        DefaultTableModel model = (DefaultTableModel) tblthongtinphong.getModel();
        model.setRowCount(0);
        for (PhongInfo ql : ArrayQL) {
            model.addRow(new Object[]{ql.getLoaitin(), ql.getLoaiphong(), ql.getGiaphong(), ql.getDiaci(), ql.getDientich()});

        }
    }
    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        PhongInfo ql = new PhongInfo();
        ql.setLoaitin(cobloaitin.getSelectedItem().toString());
        ql.setLoaiphong(cobloaiphong.getSelectedItem().toString());
        ql.setGiaphong(Double.parseDouble(txtgiaphong.getText()));
        ql.setDiaci(txtdiachi.getText());
        ql.setDientich(txtdientich.getText());
        ql.setAnh(duongdananh);
        ql.setId_phong(ArrayQL.get(vitri).getId_phong());

        ArrayQL.set(vitri, ql);
        FilDataToArrayListTable();
        if (ql.getId_phong() == 0) {
            listAdd.add(ql);
        } else {
            listUpdate.add(ql);
        }
        JOptionPane.showMessageDialog(this, "sua thanh cong");
    }//GEN-LAST:event_btnsuaActionPerformed
    public int vitri = -1;
    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        ArrayQL.remove(vitri);
        FilDataToArrayListTable();
    }//GEN-LAST:event_btnxoaActionPerformed
    public void FillDateToControl() {
        cobloaitin.setSelectedItem(ArrayQL.get(vitri).getLoaitin());
        cobloaiphong.setSelectedItem(ArrayQL.get(vitri).getLoaiphong());
        txtgiaphong.setText(String.valueOf(ArrayQL.get(vitri).getGiaphong()));
        txtdiachi.setText(ArrayQL.get(vitri).getDiaci());
        txtdientich.setText(ArrayQL.get(vitri).getDientich());
        lblanh.setIcon(ResizeImage(ArrayQL.get(vitri).getAnh()));
    }
    private void tblthongtinphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblthongtinphongMouseClicked
        vitri = tblthongtinphong.getSelectedRow();
        FillDateToControl();
    }//GEN-LAST:event_tblthongtinphongMouseClicked

    private void btnthemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemmoiActionPerformed
        // TODO add your handling code here:
        txtgiaphong.setText("");
        txtdiachi.setText("");
        txtdientich.setText("");
    }//GEN-LAST:event_btnthemmoiActionPerformed

    private void btndangtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangtinActionPerformed

        // Insert data into database
        Integer soPhongAdd = PhongDao.themPhong(listAdd);
        Integer soPhongSua = PhongDao.suaPhong(listUpdate);
        JOptionPane.showMessageDialog(this, "Đăng tin thành công!");

        if (soPhongAdd > 0) {
            // Clear input fields
            clearPhongInfo();
        }

        listAdd = new LinkedList<>();
        listUpdate = new LinkedList<>();
        displayPhongByUser();
    }//GEN-LAST:event_btndangtinActionPerformed

    private void cobloaiphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobloaiphongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cobloaiphongActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatephong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                updatephong updatep = new updatephong();
                updatep.setVisible(true);
                updatep.setResizable(false);
            }
        });
    }

    @Override
    public void setDefaultCloseOperation(int operation) {
        if (operation != DO_NOTHING_ON_CLOSE
                && operation != HIDE_ON_CLOSE
                && operation != DISPOSE_ON_CLOSE
                && operation != EXIT_ON_CLOSE) {
            throw new IllegalArgumentException("defaultCloseOperation must be"
                    + " one of: DO_NOTHING_ON_CLOSE, HIDE_ON_CLOSE,"
                    + " DISPOSE_ON_CLOSE, or EXIT_ON_CLOSE");
        }

        if (operation == EXIT_ON_CLOSE) {
            setVisible(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnanh;
    private javax.swing.JButton btndangtin;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemmoi;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cobloaiphong;
    private javax.swing.JComboBox<String> cobloaitin;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblanh;
    private javax.swing.JLabel lblbackground;
    private javax.swing.JLabel lbldiachi;
    private javax.swing.JLabel lbldientich;
    private javax.swing.JLabel lblgiaphong;
    private javax.swing.JLabel lblloaiphong;
    private javax.swing.JLabel lblloaitin;
    private javax.swing.JTable tblthongtinphong;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtdientich;
    private javax.swing.JTextField txtgiaphong;
    // End of variables declaration//GEN-END:variables

    private void displayPhongByUser() {
        this.ArrayQL = PhongDao.getPhongByUser(dangnhapInfo.getId_name());
        FilDataToArrayListTable();
    }

    private void clearPhongInfo() {
        txtgiaphong.setText("");
        txtdiachi.setText("");
        txtdientich.setText("");
        duongdananh = "";
        cobloaitin.setSelectedIndex(0);
        cobloaiphong.setSelectedIndex(0);
    }

}
